#!/usr/bin/env python
# coding: utf-8

"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class QueueData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        """
        Swagger model

        :param dict swaggerTypes: The key is attribute name and the value is attribute type.
        :param dict attributeMap: The key is attribute name and the value is json key in definition.
        """
        self.swagger_types = {
            'project_id': 'str',
            'name': 'str',
            'size': 'int',
            'total_messages': 'int',
            'total': 'int',
            'message_timeout': 'int',
            'message_expiration': 'int',
            'consistency_factor': 'str',
            'replicas': 'int',
            'type': 'str',
            'push': 'Push',
            'alerts': 'list[Alert]'
        }

        self.attribute_map = {
            'project_id': 'project_id',
            'name': 'name',
            'size': 'size',
            'total_messages': 'total_messages',
            'total': 'total',
            'message_timeout': 'message_timeout',
            'message_expiration': 'message_expiration',
            'consistency_factor': 'consistency_factor',
            'replicas': 'replicas',
            'type': 'type',
            'push': 'push',
            'alerts': 'alerts'
        }
        
        
        self.project_id = None  # str
        
        # Name of the queue
        self.name = None  # str
        
        
        self.size = None  # int
        
        
        self.total_messages = None  # int
        
        
        self.total = None  # int
        
        
        self.message_timeout = None  # int
        
        
        self.message_expiration = None  # int
        
        
        self.consistency_factor = None  # str
        
        
        self.replicas = None  # int
        
        # Types can be [multicast, unicast, pull] where multicast and unicast define a push queue. If a type isnt specified, it defaults to pull. If the push field is defined, the queue will be crated as a push queue and must contain at least one subscriber. Everything else in the push map is optional.\&quot;\n
        self.type = None  # str
        
        
        self.push = None  # Push
        
        
        self.alerts = None  # list[Alert]
        

    def __repr__(self):
        properties = []
        for p in self.__dict__:
            if p != 'swaggerTypes' and p != 'attributeMap':
                properties.append('{prop}={val!r}'.format(prop=p, val=self.__dict__[p]))

        return '<{name} {props}>'.format(name=__name__, props=' '.join(properties))


